# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - run: npm run package
    - name: Upload zipped themes
      uses: actions/upload-artifact@v2
      with:
        name: zipped-themes
        path: web-ext-artifacts/

  upload-release-assets:
    if: startsWith(github.event.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download zipped themes
        uses: actions/download-artifact@v2
        with:
          name: zipped-themes
          path: web-ext-artifacts/
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
             web-ext-artifacts/*.zip
